server:
  port: 0

spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  config:
    import: configserver:http://localhost:8888

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}:${server.port}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ["health", "info", "busrefresh", "refresh", "beans", "prometheus", "metrics"]

logging:
  level:
    org.springframework: INFO
    org.springframework.web: DEBUG
    com.safecornerscoffee.msa.user: DEBUG
    com.safecornerscoffee.msa.user.feign: DEBUG