server:
  port: 0

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}:${server.port}

logging:
  level:
    org.springframework: INFO
    org.springframework.web: DEBUG
    com.safecornerscoffee.msa: DEBUG