language: java
jdk:
  - openjdk11
cache:
  directories:
    - '$HOME/.m2/repository'

services:
  - docker
before_script:
  - docker-compose up -d
after_script:
  - docker-compse down

addons:
  sonarcloud:
    organization: "safecornerscoffee"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=safecornerscoffee_spring-cloud-with-msa