version: "3"
services:
  rabbitmq:
    image: rabbitmq:management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
    - 5672:5672
    - 15672:15672
  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: msa
      MARIADB_USER: msa
      MARIADB_PASSWORD: msa
      MARIADB_DATABASE: msa
    ports:
    - 3306:3306
