server:
  port: 0

spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  config:
    import: configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ["health", "info", "busrefresh", "httptrace", "metrics", "prometheus"]

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    org.springframework: INFO
    org.springframework.web: DEBUG
    com.safecornerscoffee.msa: DEBUG