server:
  port: 0

spring:
  application:
    name: order-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework: INFO
    org.springframework.web: DEBUG
    com.safecornerscoffee.msa: DEBUG