server:
  port: 0

spring:
  application:
    name: config-server

eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
     enabled: true
  instance:
    preferIpAddress: true
