server:
  port: 8080

spring:
  application:
    name: gateway-server

  # Configure-based Routing
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}
            - CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hello, there.
                preLogger: true
                postLogger: true
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products/(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/(?<segment>.*), /$\{segment}
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    org.springframework: info
    org.springframework.cloud.gateway: debug
    reactor.netty.http.client: debug
