server:
  port: 8080

spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/actuator/**
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/actuator/**
          filters:
            - RewritePath=/orders/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users
            - Method=POST
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - AuthorizationHeaderFilter
        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ["heath", "info", "busrefresh", "httptrace", "prometheus", "metrics"]

logging:
  level:
    org.springframework: info
    org.springframework.cloud.gateway: debug
    reactor.netty.http.client: debug
    com.safecornerscoffee.msa.gateway: debug